[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.tokenizer", "php82Extensions.fileinfo", "php82Extensions.openssl", "php82Extensions.pcre", "php82Extensions.session", "php82Extensions.hash"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "rm -rf bootstrap/cache/*.php && php artisan config:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"